### ISSUE TITLE
Correlation results repoduction

### ISSUE THREAD

**Issue by yejh123** [tmu-nlp/SEEDA#1]
Would you open-source the codes of computing the correlation results in the paper?

**Comment by imkymn** [comment]
We added code to calculate system-level correlations.

**Comment by yejh123** [comment]
> We added code to calculate system-level correlations.

Thank you~ And how about the sentence-level correlations?

**Comment by imkymn** [comment]
Regarding the sentence-level correlations, we will notify you again once they have been published.

**Comment by imkymn** [comment]
I have released the code for sentence-level correlations.
