### ISSUE TITLE
Annotation results of Step 1 of the Edit-based human evaluation.

### ISSUE THREAD

**Issue by gotutiyan** [tmu-nlp/SEEDA#2]
Thank you for publishing the ranking data.

Do you have any plans to publish the results of Step 1?

In particular, I would like to use valid/invalid annotation results for each system correction. 
(In other words, the results corresponding to "Checking system edits (@Output)" in the Figure2 of your paper.)

**Comment by imkymn** [comment]
We hadn't initially planned to release the data for step 1; however, we are considering doing so to provide additional resources, although organizing the data may take some time.

**Comment by gotutiyan** [comment]
Thank you for your response, I'm looking forward to publishing the data :)

**Comment by imkymn** [comment]
I apologize for the long wait.
I have added the results of Step 1 to `SEEDA/data/EditEval_Step1`.
If you have any questions, please feel free to ask.

**Comment by gotutiyan** [comment]
Thank you very much for providing detailed results!
