### ISSUE TITLE
Sequence of human assessments

### ISSUE THREAD

**Issue by Rr-shan** [tmu-nlp/SEEDA#3]
I can't identify the sequence of human assessments in the EW and TS file. If the order is following the sequence of this image 
![QQ截图20240513194039](https://github.com/tmu-nlp/SEEDA/assets/54834699/22197eb2-d69d-4b64-a018-397ecc63eae6)

**Comment by imkymn** [comment]
Regarding the order of the evaluation scores, it is as stated in the system-level meta-evaluation section.

> `HUMAN_SCORE` The file of human evaluation scores for each system in score/human directory. The system scores are arranged alphabetically as follows: 1: BART, 2: BERT-fuse, 3: GECToR_BERT, 4: GECToR_ens, 5: GPT-3.5, 6: INPUT, 7: LM-Critic, 8: PIE, 9: REF-F, 10: REF-M, 11: Riken-Tohoku, 12: T5, 13: TemplateGEC, 14: TransGEC, 15: UEDIN-MS.

This table is currently sorted by M2 Scorer scores, but to avoid any confusion, I will rearrange it in alphabetical order.
Thank you for your question.
