### ISSUE TITLE
data information

### ISSUE THREAD

**Issue by Rr-shan** [tmu-nlp/SEEDA#4]
![image](https://github.com/tmu-nlp/SEEDA/assets/54834699/b8c833f0-2e62-44ff-9620-4b95d59003cb)
Could you provide the results of the Scribendi Score data files?

**Comment by Rr-shan** [comment]
👀

**Comment by imkymn** [comment]
We added an evaluation score based on the Scribendi Score.

**Comment by Rr-shan** [comment]
Thank you!
