### ISSUE TITLE
sentence scores

### ISSUE THREAD

**Issue by Rr-shan** [tmu-nlp/SEEDA#5]
Is it possible that there is a problem with uploading the value, it's all None
![1716991809635](https://github.com/tmu-nlp/SEEDA/assets/54834699/0b0ae3d8-0aea-46ab-9dcc-baae46436683)

**Comment by imkymn** [comment]
Please replace "None" in the file with the evaluation scores of the corrected sentences calculated using your evaluation metric. 
The corrected sentences are located in `outputs/subset`

**Comment by Rr-shan** [comment]
Thank you! And could you provide the results of the Scribendi Score data files?
